### PR TITLE
fix #60 (shorcuts settings on linux)

### LINKED ISSUE #60: Breaks Ubuntu 17.10
As soon as the install script is executed my current session crashes and when I try to login it crashes again. I have a pretty much fresh install of Ubuntu 17.10 so hopefully it's not just some weird setup of mine that produced the error.

Here is a relevant excerpt from `/var/log/syslog`:

```
Nov 14 23:20:49 coffee gnome-session[6082]: gnome-session-binary[6082]: WARNING: App 'org.gnome.SettingsDaemon.MediaKeys.desktop' respawning too quickly
Nov 14 23:20:49 coffee gnome-session-binary[6082]: WARNING: App 'org.gnome.SettingsDaemon.MediaKeys.desktop' respawning too quickly
Nov 14 23:20:49 coffee gnome-session-binary[6082]: Unrecoverable failure in required component org.gnome.SettingsDaemon.MediaKeys.desktop
Nov 14 23:20:49 coffee gnome-session[6082]: gnome-session-binary[6082]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Nov 14 23:20:49 coffee gnome-session-binary[6082]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Nov 14 23:20:49 coffee org.a11y.atspi.Registry[1301]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Nov 14 23:20:49 coffee org.a11y.atspi.Registry[1301]:       after 21 requests (21 known processed) with 0 events remaining.
Nov 14 23:20:49 coffee kernel: [ 2291.925365] rfkill: input handler enabled
Nov 14 23:20:49 coffee gdm3: GdmDisplay: display lasted 2.453852 seconds
Nov 14 23:20:49 coffee nautilus[6292]: Error reading events from display: Broken pipe
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: could not connect to wayland server
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: (EE)
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: Fatal server error:
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: (EE) Couldn't add screen
Nov 14 23:20:49 coffee org.gnome.Shell.desktop[6113]: (EE)
```

The install script changes this `MediaKeys` variable:

```
    media_keys=org.gnome.settings-daemon.plugins.media-keys
    custom_kbd=org.gnome.settings-daemon.plugins.media-keys.custom-keybindings
    kbd_path=/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/vim-anywhere
    gsettings set $media_keys custom-keybindings "['others', '$kbd_path']"
    gsettings set $custom_kbd:$kbd_path name $name
    gsettings set $custom_kbd:$kbd_path binding $binding
    gsettings set $custom_kbd:$kbd_path command $action
``` 

I fixed my issue with the following:

```
media_keys=org.gnome.settings-daemon.plugins.media-keys
gsettings reset $media_keys custom-keybindings
```

So I was unable to test out `vim-anywhere`. I would love to try again at some point, it looks great! :smile: 
I would love to know if the bug is reproducible by others.

### PR DESCRIPTION
**Pull request by mmai**
This fixes the session crashing on ubuntu 17.10 (and probably on other versions as well).

### CODE REVIEW

**Comment by cknadler** [comment]
Hey Henri,

Thanks for the PR! I'm not very familiar with `sed`, so line 115 throws me for a bit of a loop. Any way you can break this down / document what you're doing here so I can understand? Thanks!

Cheers,
Chris

**Comment by mmai** [comment]
Hi Chris,

Thanks for this nice app

Here I use sed with the `>` character as a separator, for example `echo "hello" | sed -e "s>ell>arp>"` replaces `ell` by `arp` in `hello` and gives `harpo`.

The goal of the line is to get the current 'custom-keybindigs' configuration and to add the $kbd_path entry. So we first get the configuration with `gsettings get $media_keys custom-keybindings` which gives something like `['/org/gnome.../custom0', '/org/gnome/.../custom1/']` if there are some bindings, but  returns `@as []` if there is no binding.

There are two sed commands chained to take these two cases in account. 

The first sed command manages the case when there are some bindings : 
it replaces `']` by `', '$kbd_path']`, so  `['/org/gnome.../custom0', '/org/gnome/.../custom1/']` becomes `['/org/gnome.../custom0', '/org/gnome/.../custom1/', '$kb_path']`

The second one manages the case when there is no binding, it replaces `@as []` by `['$kbd_path']`. 

The first sed command does nothing when there is no binding because there is no `'` character in the original string `@as []`, and the second sed command does nothing when there are bindings because in this case the original string does not contain the sequence `@as []` .

I hope it makes more sense,

Henri

**Comment by base0x10** [comment]
Hey, I tested the most recent version of this PR on Fedora 27 and Ubuntu 17.10 (both of which suffer from #60 which crashes gnome on startup).  LGTM

**Comment by akkartik** [comment]
Hi @cknadler, while you guys go back and forth reviewing this PR, could you please add a note to the Readme that people probably shouldn't run the install script on Linux, or something like that? It'll save people a whole lot of pain, and probably spare you some bad vibes as well. You can always remove that prose once you're confident it's not going to fuck up people's window managers in strange ways.

**Comment by cknadler** [comment]
@mmai Awesome, thanks Henri. I'll merge this for now. If you can accomplish the same result without shelling out to `sed`, I'd happily accept another pull request. I think I understand what you're doing now, but I'm afraid I'll have a tough time maintaining this if I ever need to change it.

Thanks again!

**Pull request merged**
